version: '3.8'

services:
  src:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rails
    volumes:
      - ./miyaken-gallery:/miyaken-gallery
      # - ./ssl:/usr/local/ssl
      # - ./apache_config:/etc/httpd/conf
    ports:
      - "8080:80"
      - "${APACHE_PORT}:443"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: